#
# Arena translation messages


m.team = Team {0}

m.revive_desc = Use a Spark of Life to revive early and gain an edge in battle.

# Messages sent in-game
m.killed = {0} killed {1}.
m.suicide = {0} had a death wish.
m.fratricide = {0} killed teammate {1}!

m.left = {0} has left the match.
m.left_team = {0} ({1}) has left the match.

m.chat_all = Spectators may now chat with players.

m.locker_room = Locker Room

m.switch_team = Switch Team
