#
# Translation messages for auctions
#
# PREFIX KEY
# m.foo = message
# e.foo = error
# l.foo = label (something that is completed using another UI element)
# b.foo = button
# i.foo = tooltip (info)
# t.foo = title
# h.foo = header
# p.foo = prompt (or placeholder text)
# x.foo = optional translation that may or may not be present


t.auction = AUCTION HOUSE
b.search = Search
b.my_bids = My Bids
b.my_auctions = My Auctions
b.refresh = Refresh

#
# Search
b.prev = Prev
b.next = Next
m.all = (All)
p.search = (search text)
m.page = Page {0} of {1}

m.BID_PRICE = Bid Price
m.BUY_PRICE = Buy Price
m.END_TIME = End Time
m.STARS = Stars
m.VARIANTS = Variants
m.COUNT = Lot size

b.featured = Featured
b.by_category = By Category
b.my_recipes = My Recipes

m.featured = Featured auctions are held by the Haven Treasury. \n\n\
  They often contain rare, unique or limited time items.

m.find_auctions_by = Find Auctions by:
m.search_catagory = Search Category:
m.auction_search_results = Auction Search Results:
m.search_ready = Press 'Search' to execute your current search query.

#
# Listings

h.item = Item
h.time = Time Left
h.bid = Top Bid
h.status = Status
m.buy_now = Buy now

m.start_search = Configure your search and press 'Search'.
m.start_recipe = Select a learned recipe to search for the ingredients.
m.no_search = Your search did not match any auctions.
m.no_mybids = You have not bid on any recent auctions.
m.no_myauctions = You have no auctions.

# TimeLeft
m.cancelled = Cancelled
m.ended = Ended
m.very_short = Very short
m.short = Short
m.medium = Medium
m.long = Long
m.very_long = Very long

# Status
m.no_bid = No bids
m.bid = bids
m.high_bidder = High Bidder
m.outbid = Outbid
m.winner = Winner!
m.sold = Sold!
m.unsold = Unsold
m.remaining = Remaining: {0}


b.preview = Preview
b.buy = Buy
m.sale = Sale!
b.bid = Bid
m.or = OR
b.buy_now = Buy now
m.cancel_confirm = You will get your item back but will not be refunded your listing fee.
m.cancel_support = Are you sure?\n\n\n\
   Use your GM powers to cancel this auction and refund everyone involved?
b.cancel_cancel = Go back
b.cancel_confirm = Cancel the auction

#
# List an item

l.duration = Duration:
l.start_bid = Starting bid:
l.buy_price = Buy-it-now price:
l.listing_fee = Listing fee:
b.create = Create
p.start_bid = Crowns
p.buy_price = (None)
b.make_featured = Featured listing

m.listing_tip = The listing fee is refunded upon sale; a fee of {0}% of the sale price will be taken.
m.success = Auction created!
m.buy_success = Success! Check your mail.

m.my_current_auctions = My Current Auctions:
m.create_new_auction = Create New Auction:


#
# Durations
m.four_hours = Four hours
m.twelve_hours = 12 hours
m.one_day = One day
m.two_days = Two days
m.three_days = * Three days
m.four_days = * Four days
m.five_days = * Five days
m.six_days = * Six days
m.seven_days = * Seven days
m.infinite = * Infinite!


#
# Chat messages
m.note_outbid = Outbid: {0} ({1} crowns refunded)


#
# Various errors
e.auction_ended = The auction has already ended.
e.auction_bid = The auction may not be cancelled, it already has a bid.
e.bid_insufficient = You must bid at least {0} crowns.
e.buy_must_exceed_bid = The buy price must be greater than or equal to the starting bid, or blank.
e.search_text_short = Your search text is too short.
e.selected_updated = The selected auction has been updated.
e.no_preview = Sorry, this item cannot be previewed with your current equipment.
e.please_wait = The auction house is busy, please wait a moment and try again.
