#
# Translation messages

m.start = START

m.tier = TIER {0} (Depth {1})
m.tier_nodepth = TIER {0}

m.gate_closed = Sorry, that gate is no longer open.
m.auto_create_party = Sorry, we could not find you an available party. Do you want to start your \
  own party?

l.config_title = CONFIGURE YOUR PARTY

b.joinparty = Join Party
i.joinparty = Join a party already in progress.
b.playprivate = Create Private Party
i.playprivate = Create a party that only friends and guildmates can join.
b.formparty = Create Public Party
i.formparty = Create a party that anyone can join.
b.playsolo = Play Solo
i.playsolo = Create a party in which other players can only join if you invite them.


i.tier_2 = Requires Rank 4-2
i.tier_3 = Requires Rank 7-1
