#
# Translation messages for the Crucible program
#
# PREFIX KEY
# m.foo = message
# e.foo = error
# l.foo = label (something that is completed using another UI element)
# b.foo = button
# i.foo = tooltip (info)
# t.foo = title
# h.foo = header
# p.foo = prompt (or placeholder text)
# x.foo = optional translation that may or may not be present
#
# Or whatever makes sense.

# Love
h.love = Crucible
b.upload_love = Upload a level...
b.reupload_love = Re-upload...
b.download_love = Download
b.debug_love = Test Level
b.debug_love_private = Private Test
b.status_love = Configure...
m.no_love = No levels.
m.no_not_all = No {0} levels, try selecting All...
m.no_search = No levels match your search.
t.love_status = Configuration for {0}
m.configure_love = Configure level.
m.love_upload = Select the level type you'd like to upload.\n\
                Note: the file selection dialog will not be visible if you are playing full-screen.
m.love_reupload = Uploading a new file for the selected level.
m.love_reupload_layer = Uploading a new file for the selected level. Other layers may be updated!
m.is_public = Public testing
m.is_private = Private testing
m.play_count = Play Count: {0}
m.rating_count = 1 rating
m.rating_counts = {0} ratings
m.rating_summary = Rating: {0} ({1})
m.rating = {0} ({1})
m.no_ratings = (No ratings yet)
e.no_such_love = That level no longer exists.
m.love_delete_confirm = Are you sure? The level will be deleted.
e.rejected = Rejected!
m.love_review_confirm = Are you sure? Once in review, you will no longer be able to make changes. \
    Please completely test your level before submitting. It may take up to a week to review.
m.love_unapprove_confirm = Are you sure? You will be able to make changes again, but the approval \
    process will be started over.

g.pvp = Coliseum Crucible

# types
i.love_type = Type
m.all_types = <ALL>

# love cats
i.love_cat = Category
c.personal = My Levels
c.public_playground = Public Playground
c.public_preparing = Polishing
c.approved = Approved
c.admin_approved = Approved*
c.queue = Approval Queue
c.all = Show All
c.deleted = Recently Deleted

x.personal = All your own levels are visible here, including your private ones.
x.public_playground = The public playground is a place for learning and experimentation, and \
                      imperfect levels that are just trying out a new idea.
x.public_preparing = The polishing area is for levels considering applying to be approved.
x.approved = These levels may be in the normal game rotation, unless they are rated too low \
             after approval.

# TODO
m.status_changes = The public playground is a place for learning and experimentation.\n\
                   If you have a rating of at least {0} you can start polishing,\n\
                   and once you have a rating of {1} you can apply for approval,\n\
                   which is never guaranteed.

l.rate = Rate this level:
i.rate-1 = Thumbs Down
i.rate0 = Meh
i.rate1 = Thumbs Up
i.rate2 = Double Thumbs Up!

# LoveStatus
s.deleted = Delete!
s.locked = <Locked>
s.rejected = <Rejected>
s.private_testing = Private
s.public_playground = Public Playground
s.public_preparing = Prepare For Approval
s.ready_for_review = Ready for Review
s.in_review = <In Review>
s.approved = Approved!

m.love_arena = {0} Arena
i.fileslove = {0}s (*{1})
m.love_uploaded = Level uploaded.
m.starting_love = Testing Crucible Level...

m.love_level = {0}, uploaded by {1}|{2}
m.love_test = Crucible: {1}|Testing "{2}"

# upload status
t.upload_wait = Waiting for upload...
m.upload_wait = A file picking window is trying to show...
m.upload_wait_fs = {0}\n\n You may need to switch out of fullscreen to find it!

m.registered_knights = Crucible: Only registered knights may join the Crucible.
m.unlogged = Log in and choose a knight.
m.isguest = Guests are not permitted. Register your account, it's free!
m.reachhaven = You must reach Haven and talk to Sybil.

m.love_up_progress = Uploading...
m.love_up_error = Error: {0}
