#
# Translation messages

t.room = ROOM CONSOLE
m.place_room = Install a Room
i.place_room = Install a room at this location.
m.name_room = Name Room
i.name_room = Name the room at this location.
m.place_door = Install a Door
i.place_door = Install a door at this location.

t.room_placer = INSTALL A ROOM
t.room_list = ROOMS
#h.rooms = Rooms
h.current_room = Current Room
h.avail_rooms = Available
h.used_rooms = Used Elsewhere
m.room_added = Success! Room installed.
m.room_install_warning = You are paying to install this room. If for any reason it is \
    removed you will have to pay to install it again.

b.buy_room = Install Room
e.current_room = That is the currently installed room.

#e.deploy_limit = Sorry, the maximum number of that kind of item are already placed here.

t.door_placer = Install Door
t.door_list = DOORS
h.doors = Doors
b.buy_door = Install Door
m.door_changed = Success! Door installed!
m.door_install_warning = You are paying to install this door. If for any reason it is \
    removed you will have to pay to install it again.

t.room_name = ROOM NAMING
l.room_name = Room name:
m.room_unnamed = <Unnamed Room>

m.room_name_updated = Room name updated.

e.furni_max_deployed = There are no available units of that furnishing to deploy.

l.regenerating = Regenerating in...
e.regenerating = Design Mode is regenerating. Please try again in a moment.

e.location_already_placed = A room has already been installed at this location.
e.location_removed = That location has been removed.
e.room_already_placed = That room has already been installed at another location.
e.room_not_nameable = This room cannot be renamed.

#
# Hud furni button help
h.furni = Display your furnishings inventory.
