#
# Translation messages

m.formation = You may form a new guild for {0} crowns and {1} energy. \
  The crowns will be seeded into the guild's treasury. \
  By creating a guild \
  you will become the Guild Master and will have the ability to invite new members into \
  your guild. Guild features include:\n\
  Personal Guild Hall for Guild Members only\n\
  Guild Member chat channel\n\
  Guild Officer chat channel\n\
  Guild Member rankings\n\
  Guild Member status updates\n

m.guild_name = Guild Name:
m.form_guild = Form Guild

m.confirm_leave = Are you sure you no longer want to be a member of {0}?
m.leave_guild = Leave Guild
m.left = {0} left {1}.

m.confirm_promote = Are you sure you want to promote {0} to {1}?
m.promote_member = Promote
m.promoted = {0} promoted {1} to {2}.
m.auto_promoted = {0} auto-promoted to {1}.

m.confirm_demote = Are you sure you want to demote {0} to {1}?
m.demote_member = Demote
m.demoted = {0} demoted {1} to {2}.

m.confirm_remove = Are you sure you want to remove {0} from {1}?
m.remove_member = Remove from Guild
m.removed = {0} removed {1} from {2}.

m.guild_logon = Guild member {0} has logged on.
m.guild_logoff = Guild member {0} has logged off.

m.motd = {0} message of the day: {1}
m.motd_changed = {0} changed the message of the day: {1}

m.warn_in_default = WARNING: Your guild is in default!

#
# Formation messages

m.name_in_use = Sorry, that name is already in use.

#
# Renaming messages

t.enter_new_name = ENTER NEW GUILD NAME
t.cannot_rename = CANNOT RENAME GUILD
m.renaming = Renaming Guild...
t.rename_success = RENAME SUCCESS!
m.rename_success = Guild renamed successfully!
m.rename_too_soon = You have renamed your guild too recently.
m.rename_gms_only = Sorry, only Guild Masters may rename a guild.
m.rename_validating = Validating Guild Rename...
x.rename_desc1 = Your guild may only be renamed every 30 days.
x.rename_desc2 = The renaming item will be consumed.

m.not_in_guild = Sorry, you're not presently in a guild.

#
# Invite messages

m.invite_name = Enter the name of the knight you wish to invite:
m.friends_list = Friends List
m.invite_message_name = Enter an optional message to {0} with your invitation:
m.invite_message = Enter an optional message to include with your invitation:
m.invite_subj = Join my guild!
m.invite_low = Invite
m.invite_self = Sorry, you can't invite yourself.
m.already_in_guild = {0} is already in your guild.
m.too_many_members = Your guild cannot have more than {0} members. \n\
  Upgrades to your member limit may be purchased in the shop in your guild hall.
m.invite_pending = {0} has already been invited to join your guild.
m.invite_sent = Sent invitation to {0}.
m.joined = {0} accepted {1}'s invitation to join {2}.
e.cannot_invite_gm = You cannot invite a Game Master to join your guild.
e.guild_deleted = Sorry, that guild has been disbanded.
e.leave_current_first = You must leave your current guild before accepting this invitation.
e.guild_full = Sorry, that guild is full.
e.guild_in_default = Sorry, that guild is in-default. Try again later.
m.invitee_denied = {0} could not accept an invitation to join {1}: guild is full.

#
# Ranks

m.rank.0 = Guild Master
m.rank.1 = Officer
m.rank.2 = Veteran
m.rank.3 = Member
m.rank.4 = Recruit

#
# Popup menu

m.guild_options = Guild Options
m.no_guild = <No Guild>
m.create_guild = Create Guild
m.invite_to_guild = Invite
m.tell = Tell
m.show_treasury = Show Guild Treasury
m.edit_hall = Enter Design Mode (DEV)

#
# hall-related messages

m.hall = Guild Hall|{0}
m.design = Design Mode|{0} Guild Hall
e.design_full = Sorry, design mode is already occupied by the maximum number of editors.
e.in_default = Sorry, you cannot do that while the guild is in default.
m.hall_now_closed = {0}'s Guild Hall is no longer open to the public.
m.door = {0}\n({1})

e.statue_deploy_limit = Sorry, only {0} knight statues may be placed in a hall at once. \
   To add this statue, please remove another one.
e.item_treasury_limit = Sorry, an item you're trying to add is already at the limit for how \
                        many can be placed in a guild hall.
e.treasury_no_use = Sorry, the treasury only accepts materials used in guild crafting recipes.

#
# Guild console messages

t.console = Guild Console
t.design_console = Design Mode Console
b.console_edit = Design Mode
i.console_edit = Work with others to decorate and modify the Guild Hall.
b.console_publish = Publish
i.console_publish = Publish design changes to the Guild Hall.
b.charter = Guild Charter
i.charter = View important information about this guild.
b.member_storage = Member Storage
i.member_storage = Community item storage for members and above.
b.veteran_storage = Veteran Storage
i.veteran_storage = Community item storage for veterans and above.
b.officer_storage = Officer Storage
i.officer_storage = Community item storage for officers and above.
b.guild_shop = Birdsong Emporium
i.guild_shop = Purchase guild furnishings and upgrades using funds from the Guild Treasury.
b.guild_log = Guild Record
i.guild_log = Examine recorded events within the guild.
b.guild_help = Help and Documentation
i.guild_help = Read all about Guild Halls.
b.buy_expansions = Expand Guild Hall
i.buy_expansions = Purchase more space for the Guild Hall. Increases upkeep.
b.buy_themes = Change Theme
i.buy_themes = Change the theme for the Guild Hall.
b.buy_environments = Change Environment
i.buy_environments = Change the environment for the Guild Hall.
b.open = Open to the public
l.motd = Message of the day:
i.show_treasury = View the Guild Treasury
b.force_regen = Force Regenerate (SUPPORT ONLY)

#
# Guild log messages
b.gl_prev = Prev
b.gl_next = Next
b.gl_save = Save Complete Log to Desktop
l.gl_save_progress = Saving guild log to the desktop...
l.gl_save_error = Error writing guild log file!
l.gl_save_complete = File saved!
t.guildlog = GUILD LOG
l.gl_timestamp = Timestamp
l.gl_category = Category
l.gl_name = (Name)
l.gl_name_clean = Name
l.gl_message = Message
l.gl_page = Page {0} of {1}
m.gl_promoted = Promoted
m.gl_demoted = Demoted
l.gl_noentries = No Log Entries Found.
cat.all = (All Records)
cat.membership = Membership
cat.treasury = Treasury
cat.storage = Storage
cat.energy = Energy
cat.upkeep = Upkeep
cat.hall = Guild Hall
log.member_added = Accepted {0}'s invitation to join the guild. Welcome!
log.member_removed = Removed {0} from the guild.
log.member_left = Left the guild. Farewell!
log.member_rank_changed = {0} {1} to {2}.
log.member_auto_promoted = Was automatically promoted to {0}.
log.crowns_added = Added {0} crowns to the guild treasury.
log.mist_added = Deposited {0} energy to the energy well (new total: {1}).
log.mist_removed = Withdrew {0} mist energy from the energy well (new total: {1}).
log.energy_added = Deposited {0} energy to the energy well (new total: {1}).
log.energy_removed = Withdrew {0} energy from the energy well (new total: {1}).
log.upkeep_paid = Upkeep paid! {0} crowns removed from the guild treasury.
log.upkeep_default = Upkeep not paid! Guild Hall is in default.
log.item_added.1 = Added {1} to the Treasury.
log.item_added.n = Added {1} ({0} copies) to the Treasury.
#log.item_removed.1 = Removed {1} from guild storage.
#log.item_removed.n = Removed {1} ({0} copies) from guild storage.
log.member_item_added.1 = Added {1} to member storage.
log.member_item_added.n = Added {1} ({0} copies) to member storage.
log.member_item_removed.1 = Removed {1} from member storage.
log.member_item_removed.n = Removed {1} ({0} copies) from member storage.
log.veteran_item_added.1 = Added {1} to veteran storage.
log.veteran_item_added.n = Added {1} ({0} copies) to veteran storage.
log.veteran_item_removed.1 = Removed {1} from veteran storage.
log.veteran_item_removed.n = Removed {1} ({0} copies) from veteran storage.
log.officer_item_added.1 = Added {1} to officer storage.
log.officer_item_added.n = Added {1} ({0} copies) to officer storage.
log.officer_item_removed.1 = Removed {1} from officer storage.
log.officer_item_removed.n = Removed {1} ({0} copies) from officer storage.
log.expansion_added = Added the {0} expansion for {1} crowns, plus {2} crowns for pro-rated upkeep.
log.expansion_removed = Removed the {0} expansion.
log.theme_changed = Changed the theme to {0} for {1} crowns, replacing {2}.
log.env_changed = Changed the environment to {0} for {1} crowns, replacing {2}.
log.room_placed = Placed a {0} for {1} crowns, replacing a {2}.
log.door_placed = Placed a {0} for {1} crowns, replacing a {2}.
log.room_named = Named a room: '{0}'.
log.motd_changed = Changed the MOTD: '{0}'.
log.shop_purchase.1 = Bought {1} for {2} crowns.
log.shop_purchase.n = Bought {1} ({0} copies) for {2} crowns.
log.shop_sale.1 = Sold {1} for {2} crowns.
log.shop_sale.n = Sold {1} ({0} copies) for {2} crowns.
log.item_crafted = Crafted {0} for {1} crowns.
log.hall_published = Published the Guild Hall.
log.renamed  = Renamed the guild from '{0}' to '{1}'.

#
# Guild hall design-mode messages
m.published = The Guild Hall has been updated!

m.regen_hall = The Guild Hall is being updated...
m.regen_design = Design mode is regenerating...

#
# Bagged panel titles
t.treasury = TREASURY
t.member_storage = MEMBER
t.veteran_storage = VETERAN
t.officer_storage = OFFICER
m.treasury_warning = WARNING: Deposits made to the Treasury cannot be removed. \
                     Please review carefully before confirming.
m.storage_warning = WARNING: Items left here can be taken by any guild member of \
                     the appropriate rank.

#
# Special messages for bagged trading
m.confirm_deposit_treasury = Are you sure you want to deposit into the guild's treasury? \
   This can never be undone, not even by a GM.

#
# Energy well
t.energy_well = ENERGY WELL
l.energy = Energy: {0}
m.min_energy_deposit = Minimum Deposit: {0}
e.nsf_energy_in_well = Insufficient Energy in Energy Well.
t.deposit = DEPOSIT
b.withdraw = Withdraw {0}
b.deposit = Deposit
e.already_withdrew = You have already withdrawn from an energy well today and must wait 24 hours.

#
# mini treasury & mini upkeep panels
t.funds = GUILD TREASURY
t.upkeep = GUILD UPKEEP
h.crowns = CROWNS
h.next_upkeep = NEXT UPKEEP
m.in_default = IN DEFAULT!


#
# Expansion shop
t.expansions = EXPAND GUILD HALL
t.expansion_list = Expansions
b.buy_expansion = Buy Expansion
b.remove_expansion = Remove Expansion
h.removable_exp = Removable
h.current_exp = Other Current
h.avail_exp = Available
# TODO: remove m.remove_expansion
m.remove_expansion = Removing this expansion will lower upkeep but will \
  also remove any installed rooms in the expansion. Any furnishings in the expansion will \
  be returned to the Guild Treasury.\n\
  You will lose the following rooms: {0}
m.none = <None>
t.removing_features = REMOVING
m.removing_features = Removing this expansion will lower upkeep but will \
  also remove any installed rooms or doors in the expansion. Any furnishings in the \
  expansion will be returned to the Guild Treasury.\n\n\
  Additionally you will lose the following features: {0}
m.exp_added = Success! Expansion added.
m.exp_removed = Success! Expansion removed. Upkeep will be recalculated after your next publish.

#
# Hall Globals shop
t.global_theme = INSTALL THEMES
n.hall_theme = Themes
t.hall_theme = Changes Tileset, Lighting and Sky
b.buy_theme = Install theme
m.theme_change_warning = You are paying to install this theme. \
    If for any reason it is removed you will have to pay to install it again.
m.theme_added = Theme installed!

t.global_environment = INSTALL ENVIRONMENTS
n.hall_environment = Environments
t.hall_environment = Changes Ambient Effects
b.buy_environment = Install environment
m.environment_change_warning = You are paying to install this environment. \
    If for any reason it is removed you will have to pay to install it again.
m.environment_added = Environment installed!


#
# Guild Hall Select
t.select_guild_hall = GUILD HALLS
t.open_halls = OPEN GUILD HALLS
t.instance_capacity = CAPACITY
m.enter_hall = Enter Selected Guild Hall
m.enter_my_hall = Enter My Guild Hall
m.no_open_halls = There are no open Guild Halls

#
# Guild Scene Borders

m.border_training_hall = Guild Training Hall
m.border_training_hall_t2 = Guild Training Hall, Tier 2
m.border_training_hall_t3 = Guild Training Hall, Tier 3
