#
# Translation messages for the Project X invitation services.

t.invitations = INVITATIONS

m.description_invitations = Invite a friend to come join you in\nSpiral Knights!\n\
  Fill in their e-mail address and we'll send them an invitation to join.
m.send = SEND
m.email = E-Mail
m.your_name = Your Name

m.status_sent = Invitation sent.
m.status_invalid_email = Invalid e-mail address.
