#
# Translation messages for the Project X logon interface

m.username = ACCOUNT NAME:
m.password = ACCOUNT PASSWORD:
m.create_password = CREATE PASSWORD:
m.retype = RETYPE PASSWORD:
m.use_steam_account = Use Steam Account
m.quit = Quit
m.options = Options
m.logon = Logon

m.login_anonymous = Login as Guest

m.logging_on = Logging on...
m.logged_on = Connected.

m.tos_1 = By logging on, you acknowledge and accept the
b.help_support = Help & Support
b.forgot_password = Forgot your password?
b.game_website = Spiral Knights Website

#
# Logon response messages

m.no_such_user = No such user.
m.invalid_password = Invalid password.

m.banned = That account has been banned. You are no longer allowed to play Spiral Knights.\n\
  You were banned due to: {0}
m.deadbeat = Please go to https://billing.spiralknights.com/billing to \
  resolve a reversed payment.
m.temp_banned = This account has been temporarily suspended.
m.machine_tainted = This computer has been used by a banned account and \
  cannot be used to create new accounts.
m.no_new_free_account = You cannot create any more free accounts from this computer.
m.converted_to_steam = This account has been converted to Steam.  Select Use Steam Account to log \
  on.

m.non_public_server = The game is not currently open to the public.
m.recent_customers_only = This server is only available to customers who have spent at least \
  $4.95 on Energy in the last three months.
m.paying_customers_only = This server is only available to customers who have made a purchase \
  at some point.
m.under_maintenance = The game is currently undergoing maintenance.  Please \
	check back later.
m.downtime = Gremlins have knocked the game out of service. Please check back soon.

m.redownload = You must re-install the game.
m.version_mismatch = Your client needs to be updated. Please quit and restart.
m.version_mismatch_auto = Your client needs to be updated. It will \
  automatically update in just a moment.
m.newer_version = The game is in the process of being updated. Please try \
  again in a few minutes.
m.failed_to_secure = Failed to establish secure connection.

m.trying_next_port = Failed to connect to the server. \
  Trying an alternative port. Please wait...
m.failed_to_connect = Failed to connect to the server.
m.network_error = Either there is a temporary network outage or the \
  server is not yet fully operational. Please wait a moment before \
  reconnecting.
m.server_error = A server error caused authentication to fail.
m.peer_shutdown = The peer to which we connected is shutting down. Please wait a moment before \
  trying again.
m.peer_redirect = You are logged into a different peer. Redirecting...

m.tb_title = Temporary Ban
m.tb_info = Your account has been temporarily banned for the following reason:\n\n\
  {0}\n\n You will not be able to login again until {1}. Further violations of the \
  Terms of Service may result in a permanent ban.
m.tb_tos = Terms of Service
m.tb_quit = Return Later

m.too_many_attempts = You have made too many login attempts. Please \
  wait a few minutes before trying again.
m.session_expired = Your session has expired. Please log in on the website again and relaunch \
  the game.
m.steam_error = We experienced a problem authenticating with Steam. Please ensure that the Steam \
  client is running and that you are not logged in elsewhere.
m.steam_invalid_ticket = Invalid Steam UserID Ticket. Try logging out, quitting Steam completely \
  and trying again.
