#
# Translation messages

m.lottery_announcement = In {0}, a Birdsong Trading Co. giveaway drawing will be held amongst all \
  online players for a prize of {1}!

m.mystery_item = a mystery item
m.new_years_giveaway = a New Year's party pack

m.lottery_award = Congratulations to {0} for winning {1} in the Birdsong Trading Co. giveaway!
m.lottery_award_multi = Congratulations to all {0} winners of {1} in the Birdsong Trading Co. \
  giveaway!

s.lottery_mail_winner = Birdsong Trading Co. giveaway prize
m.lottery_mail_winner = Congratulations {0}, you have won a Birdsong Trading Co. giveaway! \
  Your prize is attached.
