#
# Monster translation messages

## Monster Details
#...................................................................................................

## BEAST FAMILY

n.alpha_ash_tail = Alpha Ash Tail
n.alpha_frostifur = Alpha Frostifur
n.alpha_voltail = Alpha Voltail
n.alpha_wolver = Alpha Wolver
n.rabid_alpha_wolver = Rabid Alpha Wolver

n.chromalisk = Chromalisk
n.electrolisk = Electrolisk
n.salamander = Salamander
n.tundralisk = Tundralisk
n.virulisk = Virulisk

n.chromalisk_whelp = Chromalisk Whelp
n.kleptolisk = Kleptolisk

n.ash_tail = Ash Tail
n.frostifur = Frostifur
n.rabid_wolver = Rabid Wolver
n.voltail = Voltail
n.wolver = Wolver

n.perma_frostifur = Perma-Frostifur
n.void_wolver = Void Wolver

n.dust_bunny = Dust Bunny
n.blech_bunny = Blech Bunny
n.jolt_bunny = Jolt Bunny
n.snow_bunny = Snow Bunny
n.toast_bunny = Toast Bunny

n.snarbolax = Snarbolax
n.rabid_snarbolax = Rabid Snarbolax

## CONSTRUCT FAMILY

n.collector = Collector
n.roarmulus_twins = Roarmulus Twins
n.red_roarmulus_twins = Red Roarmulus Twins

n.tortodrone = Tortodrone
n.tortodrone_corrupted = Tortodrone

n.blastcore = Battlepod
n.big_iron = The Big Iron

n.gun_puppy = Gun Puppy
n.gold_gun_puppy = Gold Puppy
n.plasma_dog = Plasma Dog
n.red_rover = Red Rover
n.sick_puppy = Sick Puppy
n.slush_puppy = Slush Puppy
n.spark_puppy = Sparky
n.rocket_puppy = Rocket Puppy
n.love_puppy = Love Puppy

n.shufflebot = Shufflebot

n.scuttlebot = Scuttlebot
n.cinderbot = Cinderbot
n.brumabot = Brumabot
n.surgebot = Surgebot
n.hazbot = Hazbot

n.ironwood_sentinel = Ironwood Sentinel
n.void_lumber = Void Lumber
n.lumber = Lumber
n.electreant = Electreant
n.redward = Redward
n.silversap = Silversap
n.vilewood = Vilewood

n.cryo_knight = Cryo Knight
n.firo_knight = Firo Knight
n.mecha_knight = Mecha Knight
n.poison_knight = Poison Knight
n.volt_knight = Volt Knight

n.retrode = Retrode
n.voltrode = Voltrode
n.hotrode = Hotrode
n.sleetrode = Sleetrode
n.isotrode = Isotrode

n.tentacle = Tentacle

## FIEND FAMILY

n.maulos = Maulos
n.arkus = Arkus

n.silkwing = Silkwing
n.humbug = Humbug

n.gorgo = Gorgo
n.firegut = Firegut
n.guster = Guster
n.storm_belly = Storm Belly
n.waster = Waster

n.blarful = Blarful
n.blarful_overtimer = Blarful Overtimer
n.devil_it = Devil-IT
n.devil_it_overtimer = Devil-IT Overtimer
n.devilite = Devilite
n.devilite_overtimer = Devilite Overtimer
n.firebrander = Firebrander
n.firebrander_overtimer = Firebrander Overtimer
n.layoafer = Layoafer
n.layoafer_overtimer = Layoafer Overtimer
n.pit_boss = Pit Boss
n.yesman = Yesman

n.greaver = Greaver
n.ruby_greaver = Ruby Greaver
n.pearl_greaver = Pearl Greaver
n.beryl_greaver = Beryl Greaver
n.jade_greaver = Jade Greaver

n.trojan = Trojan

## GREMLIN FAMILY

n.warmaster_seerus = Warmaster Seerus
n.razwog = Razwog
n.groat = Groat
n.herex = Herex

n.tenderfoot_thwacker = Tenderfoot Thwacker
n.ironclaw_thwacker = Ironclaw Thwacker
n.darkfang_thwacker = Darkfang Thwacker
n.void_thwacker = Void Thwacker
n.grinchlin_thwacker = Grinchlin Thwacker

n.tenderfoot_mender = Tenderfoot Mender
n.ironclaw_mender = Ironclaw Mender
n.darkfang_mender = Darkfang Mender

n.tenderfoot_scorcher = Tenderfoot Scorcher
n.ironclaw_scorcher = Ironclaw Scorcher
n.darkfang_scorcher = Darkfang Scorcher
n.gremlin_incinerator = Gremlin Incinerator
n.grinchlin_scorcher = Grinchlin Scorcher

n.tenderfoot_demo = Tenderfoot Demo
n.ironclaw_demo = Ironclaw Demo
n.darkfang_demo = Darkfang Demo

n.gremlin_knocker = Gremlin Knocker
n.gremlin_lighter = Gremlin Lighter
n.gremlin_cooler = Gremlin Cooler
n.gremlin_jumper = Gremlin Jumper
n.gremlin_choker = Gremlin Choker

n.gremlin_mortafire = Gremlin Mortafire
n.blazing_mortafire = Blazing Mortafire
n.icy_mortafire = Icy Mortafire
n.static_mortafire = Static Mortafire
n.toxic_mortafire = Toxic Mortafire

n.ghostmane_stalker = Ghostmane Stalker
n.grinchlin_stalker = Grinchlin Stalker

## SLIME FAMILY

n.royal_jelly = Royal Jelly
n.ice_queen = Ice Queen

n.jelly_cube = Jelly Cube
n.impostocube = Impostocube
n.soul_jelly = Soul Jelly
n.ice_cube = Ice Cube
n.oiler = Oiler
n.quicksilver = Quicksilver
n.toxigel = Toxigel
n.toxilargo = Toxilargo
n.void_gel = Void Gel
n.rock_jelly = Rock Jelly
n.blast_cube = Blast Cube
n.super_blast_cube = Super Blast Cube
n.ultra_blast_cube = Ultra Blast Cube
n.companion_cube = Companion Cube
n.toxoil = Toxoil
n.giant_toxoil = Giant Toxoil
n.royal_mini = Royal Mini
n.ice_mini = Ice Mini

n.jelly_green_giant = Jelly Green Giant
n.jelly_green_mini = Jelly Green Mini

n.lichen = Lichen
n.lichen_colony = Lichen Colony
n.large_lichen_colony = Large Lichen Colony
n.giant_lichen_colony = Giant Lichen Colony

n.sloom = Sloom
n.sloombargo = Sloombargo

n.polyp = Polyp
n.slick_polyp = Slick Polyp
n.polar_polyp = Polar Polyp
n.silver_polyp = Silver Polyp
n.caustic_polyp = Caustic Polyp
n.royal_polyp = Royal Polyp
n.royal_polar_polyp = Royal Polar Polyp
n.compound_polyp = Compound Polyp
n.shadow_polyp = Shadow Polyp

n.glop_drop = Glop Drop
n.spice_drop = Spice Drop
n.snow_drop = Snow Drop
n.power_drop = Power Drop
n.germ_drop = Germ Drop

n.baby_mimic = Baby Mimic
n.mimic = Treasure Mimic

## UNDEAD FAMILY

n.margrel = Margrel
n.punkin_king = Punkin King
n.gourdling = Gourdling
n.bomb_gourdling = Bomb Gourdling
n.grim_gourdling = Grim Gourdling
n.grim_scarab = Grim Scarab

n.deadnought = Deadnaught
n.fire_deadnought = Burning Deadnaught
n.freeze_deadnought = Frozen Deadnaught
n.poison_deadnought = Vile Deadnaught
n.shock_deadnought = Static Deadnaught
n.slag_guard = Slag Guard
n.almirian_royal_guard = Almirian Royal Guard
n.almirian_shadow_guard = Almirian Shadow Guard

n.bombie = Bombie
n.fire_bombie = Burning Bombie
n.freeze_bombie = Freezing Bombie
n.poison_bombie = Choking Bombie
n.shock_bombie = Surging Bombie

n.grave_scarab = Grave Scarab
n.pale_scarab = Pale Scarab
n.plague_scarab = Plague Scarab
n.silver_scarab = Silver Scarab
n.sun_scarab = Sun Scarab

n.grimalkin = Grimalkin

n.howlitzer = Howlitzer
n.chilling_howlitzer = Chilling Howlitzer
n.shocking_howlitzer = Shocking Howlitzer
n.smoking_howlitzer = Smoking Howlitzer
n.vile_howlitzer = Vile Howlitzer

n.spookat = Spookat
n.bloogato = Bloogato
n.hurkat = Hurkat
n.pepper_kat = Pepper Kat
n.statikat = Statikat
n.black_kat = Black Kat
n.mewkat = Mewkat

n.dust_zombie = Dust Zombie
n.droul = Droul
n.frankenzom = Frankenzom
n.frozen_shamber = Frozen Shambler
n.slag_walker = Slag Walker
n.carnavon = Carnavon
n.void_zombie = Void Zombie

n.phantom = Phantom

n.soldier_of_almire = Almirian Crusader


## NO FAMILY
## creep cakes, vanaduke and shadowduke, lost souls, shankle, wisps, swarm, harvester

n.vanaduke = Lord Vanaduke
n.darkfire_vanaduke = Darkfire Lord Vanaduke
n.wheel_launcher = Wheel Launcher

n.swarm_seed = Swarm Seed
n.swarm_turret = Swarm Turret

n.harvester = Apocrean Harvester
a.golden = Golden {0}

n.shankle = Shankle
n.elemental_shankle = Sage Shankle
n.piercing_shankle = Sharp Shankle
n.shadow_shankle = Dark Shankle

n.bog_wisp = Bog Wisp
n.storm_wisp = Storm Wisp
n.volcanic_wisp = Volcanic Wisp
n.winter_wisp = Winter Wisp
n.dream_wisp = Dream Wisp

n.lost_soul = Lost Soul
n.fire_soul = Fire Soul
n.freeze_soul = Frozen Soul
n.poison_soul = Poison Soul
n.shock_soul = Static Soul
n.spirits_soul = Freed Soul
n.void_soul = Void Soul

n.creep_cake = Creep Cake
n.creep_cake_mini = Mini Creep Cake
n.current_cake = Current Cake
n.batterbot = Batterbot
n.dread_velvet = Dread Velvet

n.training_bag_beast = Training Bag, Beast
n.training_bag_construct = Training Bag, Construct
n.training_bag_fiend = Training Bag, Fiend
n.training_bag_gremlin = Training Bag, Gremlin
n.training_bag_none = Training Bag
n.training_bag_slime = Training Bag, Slime
n.training_bag_undead = Training Bag, Undead

n.training_target = Training Target

# Pit Boss

m.fired_1 = Yeah... You're fired.
m.fired_2 = Your productivity is down .03% this week. You're fired.
m.fired_3 = Ahh, I'm gonna have to fire you. OK?

m.overtime_1 = Go ahead and come in on Sunday, too...
m.overtime_2 = I'm not saying to work this weekend, but everyone else is, so...
m.overtime_3 = Glad I caught you. I'm looking for someone to really rise to the challenge this \
  weekend...
m.overtime_4 = Remember, tomorrow is Hawaiian Shirt Day and every other day is Unpaid Overtime Day.

m.promotion_1 = Someone's getting a promotion...
m.promotion_2 = We could use a guy like you in management.
m.promotion_3 = I admire your ability to promote synergy.

#
# Gremlin

m.magic_missle = Ember bolt!
m.stay_close = Stay close!
m.ranged_heal = Mending!
m.hold_it_together = Hold it together!
m.catch = Catch!
m.heal = Mending!
m.heal_regen = Mending!
m.heal_target = Mending!
m.raise_dead = Arise!


## Vanaduke
#...................................................................................................

m.vanaduke_1 = What's this? More wolves hungry for the blood of Almire? Our great kingdom shall \
  never fall to the likes of beasts!

m.vanaduke_defeated = We shall never fall! We shall... never...

## Punkin King
#...................................................................................................

m.punkin_intro_1 = Tee hee hee!
m.punkin_intro_2 = What does the Punkin King have for thee...?
m.punkin_trick = TRICK!
m.punkin_treat = TREAT!

## Sputterspark
#...................................................................................................
m.great_escape_miniboss_defeat = Activate emergency...uhh...oh darn.
