#
# Particle Effects translation messages

# part_component_debuffname.dat

m.resist = -RESIST-
m.freeze = FREEZE!
m.stun = STUN!
m.shock = SHOCK!
m.poison = POISON!
m.curse = CURSE!
m.fire = FIRE!
m.sleep = SLEEP!
m.alert = -ALERT-
m.spiked = SPIKED!
m.immune = GUARD!
m.attackup = Attack Up!
m.attackdown = Attack Down!
m.defenseup = Defense Up!
m.defensedown = Defense Down!
m.countup = Count Up!
m.blastup = Blast Up!
m.healthup = Health Up!
m.speedup = Speed Up!
m.speeddown = Speed Down!
m.cleanse = Status Clear!
m.arise = ARISE!
m.maxhealth = Health At Max!
m.inventoryfull = Inventory Full!
m.bettervitapod = Current Vitapod Superior!

m.heatlost = Heat Lost!
m.heatrecovered = Heat Restored!
m.emergency_revive = Emergency Revive Activating!
