#
# Translation messages

m.name = Name
m.price = Price
m.stars = Stars
m.page = {0} / {1}
t.vendor = VENDOR

m.transaction = SHOPPING CART
m.crowns = CROWNS
m.promo_crowns = BONUS CROWNS
m.energy = ENERGY
m.tokens = TOKENS
m.empty = Empty Cart
m.checkout = Checkout

t.empty = Clear all Goods from Cart
t.confirm = Complete Transaction

t.sell_costume = Sell Costume?
p.sell_costume = Are you sure you want to sell costume items for very little crowns? This is a bad deal.

h.event_items = Limited-time items

m.cart_full = Your cart is full.
m.unsellable = That item cannot be sold.
m.nsf_tokens = Insufficient Tokens
m.cart_vitapod_adjusted = You may only equip one best vitapod: cart adjusted.
m.cart_recipe_adjusted = You will only need one of these recipes!
m.cart_recipe_learned = You have already learned this recipe!
m.cart_recipe_unlearned = You already own this recipe!
m.cart_costume_own = Warning! You already own this exact costume.

# Mini Buy Panel
#...................................................................................................

b.buy_item = Buy Item

# Guild expansions
#...................................................................................................

l.total_cost = TOTAL COST:
l.installation_cost = Installation fee:
l.upkeep_prorated = Pro-rated upkeep:


n.guild_shop = Birdsong Emporium
t.guild_shop = Furnishings and Guild Upgrades


# RESCUE CAMP
#...................................................................................................

m.rc_general = Quince
t.rc_general = Traveling Merchant

n.rc_upgrade = Ursula
t.rc_upgrade = Upgrades Merchant


# HAVEN
#...................................................................................................
m.auction_house = Auction House
m.energy_depot = Energy Depot

m.alchemy_machine = Alchemy Machine
m.event_alchemy_machine = Mysterious Alchemy Machine
m.krogmo_alchemy_machine = Krogmo Alchemy Machine
m.vise_alchemy_machine = Vise Alchemy Machine
m.sanctuary_alchemy_machine = Sanctuary Alchemy Machine
m.hunter_alchemy_machine = Armero Alchemy Machine

m.haven_weapon_1n = Quillion
m.haven_weapon_1t = Blade Merchant

m.haven_weapon_2n = Ricasso
m.haven_weapon_2t = Guns & Explosives Merchant

m.haven_armor_1n = Greave
m.haven_armor_1t = Armor Merchant

m.haven_armor_2n = Kragen
m.haven_armor_2t = Shield Merchant

m.haven_guild = Rudkin
t.haven_guild = Guild Outfitter

m.haven_upgrade = Boost
t.haven_upgrade = Special Items Merchant

m.haven_craft_2n = Vatel
m.haven_craft_2t = General Goods Merchant

m.spiral_qm = Kozma
t.spiral_qm = Spiral Quartermaster

m.token_trader = Brinks
t.token_trader = Token Trader

m.token_trader_pvp = Sullivan
t.token_trader_pvp = Coliseum Rewards Supervisor

m.accessory = Bechamel
t.accessory = Accessorizor

m.token_trader_candy = Maskwell
t.token_trader_candy = Dark Harvest Festival Prize Trader

m.candy_vendor = Bulky
t.candy_vendor = Candy Vendor

m.token_trader_cake = Maskwell
t.token_trader_cake = Anniversary Prize Trader

m.cake_vendor = Bulky
t.cake_vendor = Party Vendor

m.mon_pocket = Nonna
t.mon_pocket = Emberlight Adoption Agent

m.winterfest_vendor = Randolph
t.winterfest_vendor = Impostoclaus's Little Helper

m.slime_shop = Smitty
t.slime_shop = Casino Gift Shop

m.token_trader_torto = Maskwell
t.token_trader_torto = Tortodrone Trader

m.token_trader_spike = Barbus
t.token_trader_spike = Spike Researcher

m.slicer_recipe_trader = Torch
t.slicer_recipe_trader = Spike "Researcher"

# MOORCROFT MANOR
#...................................................................................................

m.moorcroft_armor_1n = Hector
m.moorcroft_armor_1t = Vitapod Merchant

m.moorcroft_armor_2n = Estavio
m.moorcroft_armor_2t = Vials Merchant

m.token_trader_pages = Montague
t.token_trader_pages = Historic Preservation Motivator

m.moorcroft_alchemy_machine = Moorcroft Alchemy Machine

# TRAVELING MERCHANT
#...................................................................................................

m.traveler_1 = Basil
t.traveler_1 = Traveling Merchant


# EMBERLIGHT
#...................................................................................................

n.em_general = Gracken
t.em_general = General Goods


# HALL OF HEROES
#...................................................................................................

n.hoh_cobalt = Jorin
t.hoh_cobalt = Cobalt Knight

n.hoh_striker = Echo
t.hoh_striker = Striker

n.hoh_heavy = Izola
t.hoh_heavy = Guardian

n.hoh_gunner = Daxen
t.hoh_gunner = Gunslinger

n.hoh_bomber = Remi
t.hoh_bomber = Bomber

n.hoh_piercing = Walkon
t.hoh_piercing = Piercing Defender

n.hoh_elemental = Archilus
t.hoh_elemental = Elemental Defender

n.hoh_shadow = Sylvin
t.hoh_shadow = Shadow Defender

n.hoh_specialist = Zebulon
t.hoh_specialist = The Specialist

# THE OBSIDIAN NEXUS
#...................................................................................................

m.token_trader_sigil = Lost Soul
t.token_trader_sigil = Apocrean Item Trader

m.alchemy_obelisk = Obelisk of Creation

# DEPOT TOOLTIP
#...................................................................................................

b.depotAd = Depot
m.accessoryDepotAd = Want to recover your accessory? Buy a recover ticket!
m.accessoryUseRecover = Want to recover your accessory? Use your recover ticket!
b.accessoryRecover = Use
m.unbindeDepotAd = Out of energy? Get more in the supply depot!
m.purchaseWindowDepotAd = Out of energy? Get more in the supply depot!
