#
# Translation messages

m.loadoutsummary = LOADOUT SUMMARY

m.party = PARTY
m.guild = GUILD
m.friend = FRIENDS
m.offline_up = OFFLINE

m.friends_options = Friends Options
m.add_friend = Add Friend
m.invite_steam_friend = Invite Steam Friend
m.location = {0} - {1}

# Some special whereaboutses
m.guildhall = {0} Guild Hall
m.designmode = {0} Design Mode

m.guild_options = Guild Options

t.social = SOCIAL

m.status = STATUS:
m.online = Online
#m.away = Away
#m.busy = Busy
m.offline = Offline
m.since = Since {0}

#
# Whereabouts messages
m.ready_room = Ready Room
m.pvp = Playing {0}
m.pvp_watch = Watching {0}
m.on_mission = Mission: {0} ({1})

m.enrollment = ENROLLMENT:
m.open = Open
m.locked = Locked
m.restricted = Restricted
m.full = Full

m.friends = FRIENDS
m.ignored = IGNORED

m.friendslist_low = Friends List

m.join = JOIN!
m.invite = INVITE
m.signup = SIGN UP!
m.inspect = INSPECT!

#
# Party options menu

m.party_options = Party Options
m.open_to_all = Open to Public
m.open_to_friends = Allow Friends
m.open_to_guild = Allow Guildmates
m.invite_to_party = Invite
m.go_solo = Go Solo
m.leave_party = Leave Party

#
# Note popup messages

t.notes = NOTIFICATIONS

# Other notes: to be sorted out
t.party_invite = Party Invite from {0}
t.trade_request = Trade Request
t.item_expired = Item Expiration Notice

#
# LFG notifications

t.lfg_found = Party Available
m.lfg_found = Party found, led by {0}
m.avail = Available


#
# Friend messages

m.befriend_name = Enter the name of the knight whom you would like to befriend:
m.befriend_message_name = Enter an optional message to {0} with your friend request:
m.befriend_message = Enter an optional message to include with your friend request:
m.submit_request = Submit Request
m.friend_self = Sorry, you can't be your own friend.
m.already_friend = {0} is already your friend.
m.friend_req_subj = Let's be friends!
m.friend_request_pending = You have already sent a friend request to {0}.
m.friend_request_sent = Sent friend request to {0}.
m.confirm_unfriend = Are you sure you no longer want to be friends with {0}?
m.unfriend = Remove as Friend
m.unfriended = You are no longer friends with {0}.
m.friend_unjoinable = Oops! {0} is no longer joinable.
m.friend_party_full = Oops! {0}'s party is no longer accepting new members.
m.friend_party_booted = You have been banned from {0}'s party.
m.friend_party_progress = You must wait for {0}'s party to reach depth {1}.
m.friended = You are now friends with {0}.
m.friend_logon = Your friend {0} has logged on.
m.friend_logoff = Your friend {0} has logged off.
e.cannot_friend_gm = You can't be friends with a Game Master. They are like stone.
e.maxfriends_inviter = Sorry, {0} already has the maximum number of friends.
e.maxfriends_invitee = Sorry, you already have the maximum number of friends.

#
# Steam invite messages

m.invite_persona = Select the player you wish to invite:

#
# Discord invite messages
m.discord_join_req = A discord player is asking to join your party. Please check the discord \
                     client.

#
# Auto-friending messages
# * "max" messages indicate the new knight as already reached max friend list size
# * "too_many" messages indicate the new player's FB friend has a friend list that is already at
#   max
# * "multiple" messages are sent as a batched up single message to the new knight
# * "single" messages are sent to each individual Facebook friend's first knight

m.autofriend_multiple_subject = You have {0} friends playing Spiral Knights!
m.steam = Steam
m.autofriend_single_subject = Your {0} friend is playing Spiral Knights!
m.autofriend_multiple_body = You have {0} friends that play Spiral Knights! {1}
m.autofriend_multiple_friended = These knights have automatically been made your friend:\n\
  {1}\n{2}
m.autofriend_connection = * {0} plays as {1}\n{2}
m.autofriend_multiple_too_many = Some of your {0} friends already have a full friend \
  list:\n\
  {1}\n{2}
m.autofriend_multiple_max = Your friend list is already full! You were unable to friend these \
  {0} friends at this time:\n\
  {1}\n{2}
m.autofriend_single_too_many = Your {0} friend {1} just started playing Spiral Knights as \
  {2}! You already have the maximum number of friends, so you were unable to be auto-friended.
m.autofriend_single = Your {0} friend {1} just started playing Spiral Knights as {2}! \
  You have automatically been made friends.
m.autofriend_single_max = Your {0} friend {1} just started playing Spiral Knights as {2}! \
  Unfortunately, that knight already has a full friend list, so you were unable to be auto-friended.

# Ignore messages

m.ignore = Ignore

# Party messages

m.party_leader = Party Leader
m.invite_name = Enter the name of the knight you wish to invite:
m.invite_low = Invite
m.already_in_party = {0} is already in your party.
m.not_online = There is no knight named {0} online.
m.already_invited = {0} has already been invited to your party.
m.booted = {0} has been banned from the party.
m.invited = Sent invitation to {0}.
m.party_invite = {0} has invited you to join their party.
m.party_dissolved = Oops! That party no longer exists.
m.party_full = Oops! That party is no longer accepting new members.
m.watch_full = Oops! That party is no longer accepting new watchers.
m.party_progress = {0} cannot join until the party reaches depth {1}.
m.knight_progress = You cannot join until the party reaches depth {1}.
m.confirm_go_solo = Are you sure you want to continue on alone?
m.they_already_played = {0} has already completed this mission today.
m.already_played = You have already completed this mission today.
b.go_solo = Go Solo

# Trade messages

m.not_here = There is no knight named {0} here.
m.trade_request_pending = You have already sent a trade request to {0}.
m.trade_request_sent = Sent trade request to {0}.
m.trade_request = {0} would like to trade with you.
m.trade_accept = Let's trade!
m.trade_reject = No thanks
m.trader_left = Oops! That player is no longer here.
m.trader_busy = Oops! That player is otherwise occupied.

#
# Feed messages

t.feed = EVENT HUB
g.events = Events
g.today = Today
g.this_week = This Week
g.last_week = Last Week
m.empty_feed = No recent event activity. Check back later.

m.minutes_ago.1 = {0} minute ago
m.minutes_ago.n = {0} minutes ago
m.hours_ago.1 = {0} hour ago
m.hours_ago.n = {0} hours ago
m.days_ago.1 = {0} day ago
m.days_ago.n = {0} days ago
m.weeks_ago.1 = {0} week ago
m.weeks_ago.n = {0} weeks ago

m.you = You have {1}
m.your_friend = Your friend {0} has {1}
m.your_friends = Your friends {0} have {1}
m.guildmate = Your guildmate {0} has {1}
m.guildmates = Your guildmates {0} have {1}

m.boss_desc = defeated {0} in the {1}
n.snarbolax = the Snarbolax
l.snarbolax = Gloaming Wildwoods
n.sl_snarbolax = the Rabid Snarbolax
l.sl_snarbolax = Shadow Lair, Gloaming Wildwoods
n.royal_jelly = the Royal Jelly
l.royal_jelly = Royal Jelly Palace
n.sl_royal_jelly = the Ice Queen
l.sl_royal_jelly = Shadow Lair, Royal Jelly Palace
n.roarmulus = the Roarmulus Twins
l.roarmulus = Ironclaw Munitions Factory
n.sl_roarmulus = the Red Roarmulus Twins
l.sl_roarmulus = Shadow Lair, Ironclaw Munitions Factory
n.vanaduke = Lord Vanaduke
l.vanaduke = Firestorm Citadel
n.sl_vanaduke = Darkfire Vanaduke
l.sl_vanaduke = Shadow Lair, Firestorm Citadel

m.progress_haven = reached Haven.
m.progress_tier_2 = gained Tier 2 clearance.
m.progress_tier_3 = gained Tier 3 clearance.

m.achievement = unlocked the achievement: {0}
m.guild_join = joined the guild {0}
m.guild_promote = been promoted to {0}
m.rank_earned = reached the {0} rank

m.earned_crowns = become the new Crown King, having earned {0} crowns in the past 7 days!
m.levels_completed = become the new Level Leader, having completed {0} levels in the past 7 days!
m.pvp_played = become the new Coliseum Champion, having played {0} games of {1} in the past 7 days!
m.high_scores = High Scores!
m.earned_prestige = become the Most Prestigious, having earned {0} prestige in the past 7 days!

m.crown_king = Crown King
m.level_leader = Level Leader
m.coliseum_champion = Coliseum Champion
m.levels = Levels
m.crowns = Crowns
m.most_prestigious = Most Prestigious
m.prestige = Prestige

m.join_friend = Join your friend {0} at depth {1} in the {2} Gate!
m.join_guild = Join your guildmate {0} at depth {1} in the {2} Gate!
m.join_friend_mission = Join your friend {0} at depth {1} on the Mission: {2} ({3})
m.join_guild_mission = Join your guildmate {0} at depth {1} on the Mission: {2} ({3})
m.play_pvp = Sign up for a game of {0} {1} in the Coliseum!
m.attempt_mission = Start Mission: {0}
