#
# Status conditions

m.stun = Stun
m.poison = Poison
m.fire = Fire
m.freeze = Freeze
m.shock = Shock
m.curse = Curse
m.blind = Blind
m.muddle = Muddle
m.sleep = Sleep
m.petrify = Petrify
m.jelly = Jelly
m.doom = Doom
m.charm = Charm

m.resist = {0} Resistance
m.weak = {0} Weakness
