#
# Translation messages

m.rotating_gate_name = {0} {1} Gate

#
# Rotating gate color names

m.iron = Iron
m.silver = Silver
m.dark = Dark
m.emerald = Emerald
m.ruby = Ruby
m.sapphire = Sapphire
m.diamond = Diamond
m.onyx = Onyx
m.amber = Amber
m.coral = Coral
m.golden = Golden
m.jade = Jade
m.copper = Copper

#
# Rotating gate icon names

m.bishop = Bishop
m.clover = Clover
m.falcon = Falcon
m.king = King
m.knight = Knight
m.lion = Lion
m.pawn = Pawn
m.phantom = Phantom
m.queen = Queen
m.rook = Rook
m.serpent = Serpent
m.skull = Skull
m.sun = Sun
m.titan = Titan

#
# Themes (currently unused)
m.theme_unk = ???
m.theme_slime = SLIME
m.theme_beast = BEAST
m.theme_undead = UNDEAD
m.theme_fiend = FIEND
m.theme_gremlin = GREMLIN
m.theme_construct = CONSTRUCT
m.theme_fire = FIRE
m.theme_freeze = FREEZE
m.theme_shock = SHOCK
m.theme_curse = CURSE
m.theme_sleep = SLEEP
m.theme_poison = POISON

#
# Town names
#..................................................................................................

m.haven = Haven
m.rescue_camp = Rescue Camp

#
# Town scene names
#..................................................................................................

m.haven_town_square = Haven|Town Square
m.haven_bazaar = Haven|Bazaar
m.haven_arcade = Haven|Arcade
m.haven_eastside = Haven|Garrison
m.rescue_camp_central = Rescue Camp|Pod Town
m.rescue_camp_arcade = Rescue Camp|Training Grounds
m.rescue_camp_state_1 = Rescue Camp|Before Night Falls
m.rescue_camp_state_2 = Rescue Camp|Light in the Darkness

#
# Town scene borders
#..................................................................................................

m.border_arcade = Arcade
m.border_bazaar = Bazaar
m.border_town_square = Town Square
m.border_eastside = Garrison
m.border_rescue_camp = Rescue Camp
m.border_haven = Haven
m.border_training_hall = Advanced Training Hall
m.border_hoh = Hall of Heroes
m.border_guildhall = Guild Hall
m.border_spirallab = Lab

#
# Town descriptions
#..................................................................................................

m.haven_desc = A peaceful town that is home to the Strangers. These salvagers offer the Spiral \
  Knights sanctuary in return for the treasures that they acquire while investigating the \
  Clockworks. Haven is also heavily populated with snipes, bulbous little birds with a \
  curious means of locomotion.

m.rescue_camp_desc = The Rescue Camp serves as a refuge for newly dropped Spiral Knights. It \
  offers a few creature comforts as well as a training facility to prepare recruits for \
  their journey to Haven.
