#
# Translation messages

m.dismiss_tip = Close Trade window
m.confirm_tip = Confirm your Transaction
m.crowns_tip = Crowns
m.energy_tip = Energy

m.trade_got = Trade Successful! You got ({0}).
m.trade_gave = You gave ({0}).

m.item_desc.1 = {1}
m.item_desc.n = {0}x {1}

m.first_combine = {0} and {1}
m.combine = {0}, {1}

m.sale = Sale!

t.cart = TRANSACTION
b.empty = Empty
i.empty = Clear the transaction
i.confirm = Complete the transaction
e.cart_full = The cart is full.
e.cart_removed.1 = NOTE: a {1} was removed from the cart.
e.cart_removed.n =  NOTE: a stack (of {0}) of {1} was removed from the cart.
